services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: parser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
      - 6000:5432
    expose:
      - 6000
