services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: parser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432
      - 6000:5432
    expose:
      - 6000
  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379
    expose:
      - 6380