"""empty message

Revision ID: 30d035ffe2a9
Revises: ed549592d8ce
Create Date: 2023-08-28 19:08:18.629785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30d035ffe2a9"
down_revision = "ed549592d8ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "viewedpost",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("viewedpost")
    # ### end Alembic commands ###
