"""empty message

Revision ID: 308641f41bc2
Revises: 7bfce6e58920
Create Date: 2023-05-22 19:47:53.557797

"""
from alembic import op
from db.models import LanguageEnum
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308641f41bc2'
down_revision = '7bfce6e58920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'words',
        sa.Column(
            'language',
            sa.Enum('ru', 'en', 'ge', name='languageenum', native_enum=False),
            nullable=True,
        )
    )

    bind = op.get_bind()
    meta = sa.MetaData()
    meta.reflect(
        bind=bind,
        only=("words", "languages"),
    )
    words_table = meta.tables["words"]
    languages_table = meta.tables["languages"]

    stmt = sa.select(languages_table.c.name, languages_table.c.id)
    languages_hashmap = dict(tuple(bind.execute(stmt))) # dict[name, id]

    if languages_hashmap:
        update_stmt = sa.update(words_table).values(
            language=sa.case(
                *[
                    (
                        languages_hashmap[enum.name] == words_table.c.language_id, 
                        enum.name,
                    )
                    for enum in LanguageEnum
                    if enum.name in languages_hashmap
                ],
                else_=LanguageEnum.ru.name,
            )
        )
        bind.execute(update_stmt)

    op.alter_column('words', "language", nullable=False)

    op.drop_table('translates')
    op.drop_constraint('words_language_id_fkey', 'words', type_='foreignkey')
    op.drop_column('words', 'language_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('words_language_id_fkey', 'words', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.drop_column('words', 'language')
    op.create_table('translates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_language_id'], ['languages.id'], name='translates_from_language_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_language_id'], ['languages.id'], name='translates_to_language_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='translates_pkey')
    )
    # ### end Alembic commands ###
