"""empty message

Revision ID: c437e7eb4b22
Revises: 308641f41bc2
Create Date: 2023-07-06 20:23:15.740457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c437e7eb4b22"
down_revision = "308641f41bc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###
