"""empty message

Revision ID: c176c738a4a5
Revises: 93d2ec9ac54a
Create Date: 2022-12-23 20:05:21.523822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c176c738a4a5'
down_revision = '93d2ec9ac54a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favoriteword_translate_id_fkey', 'favoriteword', type_='foreignkey')
    op.drop_column('favoriteword', 'translate_id')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('words', sa.Column('translate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'words', 'translates', ['translate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_column('words', 'translate_id')
    op.drop_column('users', 'is_active')
    op.add_column('favoriteword', sa.Column('translate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favoriteword_translate_id_fkey', 'favoriteword', 'translates', ['translate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
