"""empty message

Revision ID: cfad73abf1d6
Revises: 37c4de6b0df7
Create Date: 2023-04-03 19:06:15.985046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfad73abf1d6"
down_revision = "37c4de6b0df7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posttags", "tag_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("posttags", "post_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("posttags", "id")
    op.create_primary_key("posttags_pk", "posttags", ["tag_id", "post_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("posttags_pk", "posttags", type_="primary")
    op.add_column(
        "posttags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.alter_column("posttags", "post_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("posttags", "tag_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
